"""Domain layer: enums, frozen constants, and canonical Pydantic models."""

from .models import (
    CnesCanonicalRow,
    IbgePopulationRow,
    PniObservation,
    SivepCanonicalRow,
    SourceContractDocument,
    SourceFileEntry,
    SourceFileMetadata,
)
from .source import (
    CNES_BED_METRIC_FIELD,
    CNES_COMPETENCIA,
    CNES_COMPLEMENTARY_BED_TYPE,
    CNES_CRITICAL_SOURCE_COLUMNS,
    CNES_ICU_ALLOWLIST,
    CNES_REQUIRED_SOURCE_COLUMNS,
    CNES_SOURCE_TO_CANONICAL,
    IBGE_BRAZIL_POPULATION,
    IBGE_GEOGRAPHY,
    IBGE_REFERENCE_DATE,
    IBGE_REFERENCE_YEAR,
    PNI_CAMPAIGN_YEAR,
    PNI_ELIGIBLE_SCOPE,
    QUALITY_THRESHOLD_AVAILABLE,
    QUALITY_THRESHOLD_WARNING,
    SIVEP_AGENT_FACING_FORBIDDEN,
    SIVEP_CANONICAL_COMPLETENESS_FIELDS,
    SIVEP_CRITICAL_SOURCE_COLUMNS,
    SIVEP_EVOLUTION_CODE_MATRIX,
    SIVEP_MINIMIZATION_ALLOWLIST,
    SIVEP_REQUIRED_SOURCE_COLUMNS,
    SIVEP_SOURCE_TO_CANONICAL,
    SIVEP_YESNO_CODE_MATRIX,
    CnesCanonicalField,
    DedupReason,
    IbgeCanonicalField,
    NullReason,
    PniCanonicalField,
    QualityState,
    QuarantineReason,
    SivepCanonicalField,
    SivepEvolutionCode,
    SivepYesNoCode,
    SourceFamily,
    SourceStatus,
)

__all__ = [
    # Models
    "CnesCanonicalRow",
    "IbgePopulationRow",
    "PniObservation",
    "SivepCanonicalRow",
    "SourceContractDocument",
    "SourceFileEntry",
    "SourceFileMetadata",
    # Enums
    "CnesCanonicalField",
    "DedupReason",
    "IbgeCanonicalField",
    "NullReason",
    "PniCanonicalField",
    "QualityState",
    "QuarantineReason",
    "SivepCanonicalField",
    "SivepEvolutionCode",
    "SivepYesNoCode",
    "SourceFamily",
    "SourceStatus",
    # Constants
    "CNES_BED_METRIC_FIELD",
    "CNES_COMPETENCIA",
    "CNES_COMPLEMENTARY_BED_TYPE",
    "CNES_CRITICAL_SOURCE_COLUMNS",
    "CNES_ICU_ALLOWLIST",
    "CNES_REQUIRED_SOURCE_COLUMNS",
    "CNES_SOURCE_TO_CANONICAL",
    "IBGE_BRAZIL_POPULATION",
    "IBGE_GEOGRAPHY",
    "IBGE_REFERENCE_DATE",
    "IBGE_REFERENCE_YEAR",
    "PNI_CAMPAIGN_YEAR",
    "PNI_ELIGIBLE_SCOPE",
    "QUALITY_THRESHOLD_AVAILABLE",
    "QUALITY_THRESHOLD_WARNING",
    "SIVEP_AGENT_FACING_FORBIDDEN",
    "SIVEP_CANONICAL_COMPLETENESS_FIELDS",
    "SIVEP_CRITICAL_SOURCE_COLUMNS",
    "SIVEP_EVOLUTION_CODE_MATRIX",
    "SIVEP_MINIMIZATION_ALLOWLIST",
    "SIVEP_REQUIRED_SOURCE_COLUMNS",
    "SIVEP_SOURCE_TO_CANONICAL",
    "SIVEP_YESNO_CODE_MATRIX",
]
